# Generated by Django 3.1.1 on 2020-10-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0002_userap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userap',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='passportid',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='title',
        ),
    ]
