# Generated by Django 3.1.1 on 2020-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0003_auto_20201028_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userap',
        ),
    ]
