# Generated by Django 3.1.1 on 2020-10-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0005_userap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userap',
        ),
    ]
