# Generated by Django 3.1.1 on 2020-10-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0008_auto_20201029_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userap',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
