# Generated by Django 3.1.1 on 2020-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0009_auto_20201029_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userap',
            name='affiliation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='passportid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='phoneno',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userap',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
