# Generated by Django 3.1.1 on 2020-10-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0010_auto_20201029_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userap',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userap',
            name='title',
        ),
    ]
