# Generated by Django 3.1.1 on 2020-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0011_auto_20201029_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userap',
            name='affiliation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userap',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
