# Generated by Django 3.1.1 on 2020-10-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0012_auto_20201029_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userap',
        ),
    ]
