# Generated by Django 3.1.1 on 2020-10-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0018_userap'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCIIS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.CharField(max_length=255)),
                ('paper_title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('paper_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='authors',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='gender',
        ),
    ]
