# Generated by Django 3.1.1 on 2020-10-29 19:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0019_auto_20201029_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='paperauthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.CharField(max_length=255)),
                ('paper_title', models.CharField(max_length=255)),
                ('paper_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
