# Generated by Django 3.1.1 on 2020-10-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0020_paperauthor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paperauthor',
        ),
    ]
