# Generated by Django 3.1.1 on 2020-10-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0022_paperauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='admin',
        ),
        migrations.DeleteModel(
            name='userap',
        ),
        migrations.AlterModelManagers(
            name='paperauthor',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
