# Generated by Django 3.1.1 on 2020-11-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0024_authors_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentpaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_id', models.CharField(max_length=255)),
                ('paper_id', models.CharField(max_length=255)),
                ('paper_title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('paper_type', models.CharField(max_length=255)),
                ('author_type', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('email_add', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
