# Generated by Django 3.1.1 on 2020-11-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0027_paymentpaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paymentpaper',
        ),
    ]
