# Generated by Django 3.1.1 on 2020-11-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0033_paymentpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpaper',
            name='last_payment',
        ),
    ]
