# Generated by Django 3.1.2 on 2020-11-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciis_app', '0035_memberparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvalauthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billid', models.CharField(max_length=255)),
                ('papertitle', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('editby', models.CharField(max_length=255)),
                ('statusapproval', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Approvalpp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billid', models.CharField(max_length=255)),
                ('paperlist', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('editby', models.CharField(max_length=255)),
                ('statusapproval', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
